name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v4  # Using latest version to avoid Node.js deprecation
      with:
        python-version: '3.10'

    - name: Install Miniconda
      uses: goanpeca/setup-miniconda@v2  # Updated to v2 to avoid Node.js 12 deprecation
      with:
        auto-update-conda: true
        python-version: '3.10'
        channels: defaults  # Explicitly specify the default channel

    - name: Create or Update Conda Environment
      run: |
        conda env update --file environment.yml --name base
        source $CONDA/bin/activate base  # Ensures conda is activated for following steps

    - name: Lint with flake8
      run: |
        conda install -y flake8  # Ensure flake8 is installed
        # Check for syntax errors and undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # Treat all other errors as warnings
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Test with pytest
      run: |
        conda install -y pytest  # Ensure pytest is installed
        pytest
